version: 2
updates:
  - package-ecosystem: maven
    directory: "/" # pom.xml file is in the project root folder
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "mvn"
    open-pull-requests-limit: 25 # Maximum number of open pull requests
